# Generated by Django 4.2.10 on 2026-02-15 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "speed_ms",
                    models.FloatField(help_text="Current speed in meters per second"),
                ),
                (
                    "direction_degrees",
                    models.FloatField(
                        help_text="Current direction in degrees (0-360, meteorological convention)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                    ),
                ),
                (
                    "u_component",
                    models.FloatField(
                        blank=True, help_text="East-west component (m/s)", null=True
                    ),
                ),
                (
                    "v_component",
                    models.FloatField(
                        blank=True, help_text="North-south component (m/s)", null=True
                    ),
                ),
                (
                    "quality_flag",
                    models.CharField(
                        blank=True,
                        help_text="Data quality indicator from source",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_fetch", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IngestionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_fetched", models.IntegerField(default=0)),
                ("records_inserted", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "task_id",
                    models.CharField(
                        blank=True, help_text="Celery task ID", max_length=255
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                (
                    "depth_meters",
                    models.FloatField(
                        blank=True,
                        help_text="Depth in meters (negative for below sea level)",
                        null=True,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemperatureObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "temperature_celsius",
                    models.FloatField(help_text="Temperature in degrees Celsius"),
                ),
                (
                    "quality_flag",
                    models.CharField(
                        blank=True,
                        help_text="Data quality indicator from source",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_observations",
                        to="api.location",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_observations",
                        to="api.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SalinityObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "salinity_psu",
                    models.FloatField(
                        help_text="Salinity in Practical Salinity Units (PSU)"
                    ),
                ),
                (
                    "quality_flag",
                    models.CharField(
                        blank=True,
                        help_text="Data quality indicator from source",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salinity_observations",
                        to="api.location",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salinity_observations",
                        to="api.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["latitude", "longitude"], name="api_locatio_latitud_670fa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["region"], name="api_locatio_region_249cd7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("latitude", "longitude", "depth_meters")},
        ),
        migrations.AddField(
            model_name="ingestionlog",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingestion_logs",
                to="api.datasource",
            ),
        ),
        migrations.AddField(
            model_name="currentobservation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_observations",
                to="api.location",
            ),
        ),
        migrations.AddField(
            model_name="currentobservation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_observations",
                to="api.datasource",
            ),
        ),
        migrations.AddIndex(
            model_name="temperatureobservation",
            index=models.Index(
                fields=["-timestamp"], name="api_tempera_timesta_da9ecd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="temperatureobservation",
            index=models.Index(
                fields=["location", "-timestamp"], name="api_tempera_locatio_bd34f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="temperatureobservation",
            unique_together={("location", "source", "timestamp")},
        ),
        migrations.AddIndex(
            model_name="salinityobservation",
            index=models.Index(
                fields=["-timestamp"], name="api_salinit_timesta_3078f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salinityobservation",
            index=models.Index(
                fields=["location", "-timestamp"], name="api_salinit_locatio_75db2c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salinityobservation",
            unique_together={("location", "source", "timestamp")},
        ),
        migrations.AddIndex(
            model_name="ingestionlog",
            index=models.Index(
                fields=["-started_at"], name="api_ingesti_started_e831b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionlog",
            index=models.Index(fields=["status"], name="api_ingesti_status_338260_idx"),
        ),
        migrations.AddIndex(
            model_name="currentobservation",
            index=models.Index(
                fields=["-timestamp"], name="api_current_timesta_abca08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="currentobservation",
            index=models.Index(
                fields=["location", "-timestamp"], name="api_current_locatio_27446d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="currentobservation",
            unique_together={("location", "source", "timestamp")},
        ),
    ]
